* Idee di cui voglio parlare
- Focalizzarsi sulla mobilità ibrida e quindi usare il sistema di WHR per produrre energia elettrica. Questo permetterebbe di pensare a una turbina ad azione e non scroll, possibile aumento dell'efficenza. Ibrido futuro?
- Quanto ci perdiamo con lo scroll? La penalità di peso è eccessiva?


* Introduction to the problem
On-road vehicles, which convert around one third of the fuel energy into useful mechanical energy for propulsion, are moving energy conversion systems that generate considerable waste heat. Due to the inefficiency of the internal combustion engine, around 60-70% of the fuel energy is wasted in the form of heat.
Rankine cycle has a great potential to be applied to harvest waste heat from automobiles. However, different from other low-grade waste heat sources, vehicles have limited space for the RC system integration and the waste heat is relatively unstable.
It has been estimated that the thermal efficiency of a modern IC engine is limited to 20-40% while 33% of the fuel energy from a typical medium-size passenger vehicle is carried away by exhaust gases and 29% is carried away by engine cooling water in urban traffic conditions. Depending on engine type and operating conditions, the IC exhaust gas temperature usually varies from 500 to 900 °C and engine cooling water temperature is around 100 °C.

There are different possibile technologies that are being researched in order to 
[Zhou Dede Joshi]


* Possibile solutions
** Rankine cycle
The RC system is an interesting system to harvest part of the wasted energy. An RC system is made of four main components:
- Evaporator
- Expander
- Condenser
- Pump

The waste heat is used in the evaporator to vaporize the working fluid and convert the heat in mechanical work in the expander.
Extensive work has been poured in RC + ICE combinations, leading to fuel saving in the order of 10 - 15% when applied to truck diesel engines.

RC are system widely adopted in a large range of WHR situations, however heat sources on vehicles are different from other typical industrial heat sources, which are stable and no space limitation for the RC system. To be technically feasible for vehicle RC application, the cycle system should be kept as simple as possible and utilize components that already exist in the vehicles in order to reduce the added expense, weight and complexity of the system. Besides, the temperature ranges of the two main heat sources on vehicles are significantly different which requires special treatment.

*** Possible configurations - advantages and disadvantages

*[INSERISCI FIGURE DA TOYOTA]*

The most common and simple structure utilizes the exhaust gas as the only heat source to evaporate the working fluid. The second structure adds another heat exchanger (recuperator) before the evaporator, using the steam from the expander to preheat the working fluid. A third structure uses waste heat from engine coolant to preheat the working fluid. The regenerative preheating of structure 2 requires a very complex liquid-gas heat exchanger with high exchange surfaces, while the preheater in structure 3 only requires a simple liquid-liquid heat exchanger.
There have been contradicting conclusions about the effect of preheating using engine coolant on the RC system efficiency. Based on Vaja and Gambarotta’s work, the RC system with a preheater allows a net increase in power output, compared to structure 1, of 10% to 35%, depending on which working fluid is chosen. Alberto Boretti also showed a 8.2% fuel economy improvement using engine coolant to preheat the RC cycle, compared to a 6.4% improvement when only exhaust gas is used to boil the working fluid. Arias et al. also compared the combined exhaust and engine coolant heat recovery system with the exhaust only structure. It was found that the additional power recovered from the engine coolant system was 20W out of a total 2140W, which is around 1% improvement.
It was argued that the reason why it is not advantageous to build combined engine coolant and exhaust gas waste heat recovery system is due to the constraint imposed on the engine coolant temperature, around 100 °C, is not a good match for the working fluid preheating. Duparchy et al. also analyzed the waste heat recovery potential for engine cooling water and exhaust gas from both energy and exergy points of view. It was found that the proportion of thermal energy carried by exhaust gas is comparable with that dissipated by engine cooling water, which means these two sources are roughly equivalent from the energy point of view. However, exhaust gas shows a much greater recovery potential in terms of exergy. The main reason why opposite conclusions were drawn from different studies is that different working fluid is selected for the RC system. For organic fluids, the preheating energy ranges 30% to 50% of the total obtained energy while it is only about 10% for water.

There are two additional configurations possible for WHR. Instead of using engine coolant to preheat the working  uid, the engine block, which has higher temperature, is used to partially evaporate the working fluid. For this structure, complete evaporation of the working  uid inside the engine block should be prevented. It should reach intermediate boiling in the engine block, so that two-phase mixture would flow out of the engine block and into the evaporator to complete the boiling and superheating process by exhaust gas. The second option is to build separate system loops and use different working fluids to match the speci c characteristics of engine coolant and exhaust gas. This system has been developed by BMW, in which waster was used as the medium in the high-temperature (HT) loop and ethanol as working fluid in the low-temperature (LT) loop. The dual loop system can utilize the full potential of the waste energy with the disadvantage of large system volume and system complexity. Another RC system which integrated with engine cooling, this system minimized the number of required components by adopting an evaporative engine cooling structure and a refrigerant as the working fluid, so that the engine functioned as an evaporator and the existing radiator worked as a condenser. The only extra component added to the system is an expander for power conversion. However, this structure requires a modification of the existing engine cooling system, while the current engine cooling technology is quite mature and widely taken and has been using 50/50 water ethylene glycol as the coolant for decades.

When selecting the different configurations, different factors have to be take into consideration as the maximization of the recovered energy is not the only objective to pursue. System complexity, component volume and weight, and the resulted extra cost added to the vehicles and the payback period are also big concerns.

*** Applications to passenger vehicles to date

**** Possible efficiency improvements
Two improvements are mainly used in the literature to asses the impact of RC systems: /thermal efficiency/ and /mechanical efficiency/.
Thermal efficiency is defined as 
\begin{equation}
\eta_{th} = \frac{W_{RC}}{m_{fuel} \cdot LHV}
\end{equation}
while mechanical efficiency is defined as 
\begin{equation}
\eta_{m} = \frac{W_{RC}}{P_{e}}
\end{equation}

Assuming one third of the total fuel energy is transferred to mechanical power output, which is a typical value for modern internal combustion engine, then usually the thermal efficiency is about one third of the mechanical efficiency.

**** Historical review
| Year | Researcher           | Technology           | % power recovered | $\Delta$ c thermal $\eta$ | $\Delta$ mechanical $\eta$ |
|------+----------------------+----------------------+-------------------+---------------------------+----------------------------|
| 1993 | Toyota               |                      |                3% |                        1% |                            |
|      | Chammas and Clodic   | steam RC             |                   |                        4% |                            |
|      | Chammas and Clodic   | organic RC           |                   |                        5% |                            |
|      | Arias, Shedd, Jester | System 4             |              5.5% |       7.5% da controllare |                            |
| 2007 | Honda R&D            | RC with hybrid       |                   |   28.9% - 32.7% @100 km/h |                            |
| 2008 | BMW                  | turbosteamer         |           10-15 % |                      5.7% |                            |
| 2012 | BMW                  | turbosteamer 2       |                6% |                        2% |                            |
|      | He et al.            | Kalina cycle         |                   |                  12-17.3% |                            |
|      | Wand et al.          | Dual loop + extra HX |          14 - 40% |                      3-6% |                            |
|      | Domingues et al.     | Simplest RC system   |                   |                           | 2.64 - 6.96%               |
                                                                                                                                  
                                                                                                                                 
*** Expanders
Critical aspect that has to be chosen carefully. Many factors need to be considered during the process of expander selection for a RC system targeting passenger vehicles, e.g. inlet and outlet working conditions, pressure ratio, power output, working  uid, weight, volume, cost, reliability, isentropic ef ciency, lubrication requirement, complexity, rotational speed, etc. In general, expander can be categorized into two types: velocity type, e.g. axial turbine expander, and volume type, e.g. scroll expander, screw expander and reciprocal piston expander.

**** Turbine expander
A turbine expander is rotary machine that converts the kinetic energy carried by a  uid stream into mechanical energy when it passes through a set of blades. Commercial micro-turbines available but not widely used (Domingues). The reduced mass and overall dimensions made the turbine one of the most appropriate expander for a RC vehicle waste heat recovery application. Due to the lack of commercial micro-turbine expanders, most researchers used their in-house speci cally designed turbine to test their RC system, usually impulse turbines. BMW’s second generation Turbosteamer  adopted a speci cally designed two-stage impulse turbine integrated with an electric generator for their RC system, see Figure 8. The turbine works in the pressure range of 6-10 bar and the rotary speed is about 50,000 to 100,000 rpm. The electrical power output of the unit is about a 2 kW. Compared to a scaled-down reaction turbine which is generally used in power plants, the impulse turbine design signi cantly reduces the  ow leakage. Lubrication free is another advantage of this design compared to volumetric expansion machines.

In general, the advantages of a turbine expander include compact structure, light weight and high ef ciency. However, the design and manufacturing of turbine is very dif cult, which leads to a relatively higher cost and the turbine ef ciency decreases signi cantly under off-design conditions. Besides, a turbine expander puts more constraints to the working  uid selection since a turbine cannot bear two-phase condition. Therefore if the heat addition is variable, the wetness in the expansion process may become uncontrollable and the droplets may damage the turbine blades. Also, a speed reduction gearbox might be required if the turbine outputs the mechanical energy directly to the crank shaft due to the speed mismatch. It is suggested that turbine expanders are preferred to be combined with electrical generators for energy conversion and storage, which make it a practical solution for hybrid vehicles

**** Scroll Expander
Scroll expander is one of the displacement type expanding machines, which are characterized by lower  ow rates, higher pressure ratios and much lower rotational speeds than turbo-machines. Advantages of this kind of technology are compact structure, reliability, fewer moving parts, lower level of noise and vibration. Besides, compare to turbine expander, these displacement type machines can tolerate two-phase conditions, which may difficult to be avoided at the end of the expansion considering the dynamic operating conditions in vehicles.
For RC system with small power output, leakage of the working  uid was the dominant cause of low ef ciency of scroll expander. The first RC application to passenger vehicle study from Toyota adopted a scroll expander which had an inlet volume of 40 cc and an expansion ratio of 2. The size of the scroll expander is 120 mm by 190 mm. The maximum expander efficiency reached in the study is approximately 50%. It was found that the expander ef ciency decreases as the revolution became lower than 1000 rpm due to the deterioration of sealing at low revolution speed which led to leakage of the working fluid.

**** Screw Expander
This type of expander is composed of a pair of meshing helical rotors, packing within a case with approximately 50 μm clearances. When the rotors rotate, the volume trapped between the rotors and the casing changes, which makes the fluid volume either increase or decrease, depending on the rotational direction. However, micro-scale screw expander (<10 kWe) for vehicle application is hard to be obtained in the current market and few reports from open literature were found for screw expander application to RC system with power output lower than 10 kWe.
In general, screw expander can tolerate two-phase flow and is highly efficient in off-design conditions. However, like other positive displacement devices, the seal is critical to prevent internal leakage. Besides, lubrication is required to avoid direct contact but also achieve a seal between the lobes of the two rotors, which makes it relatively more expensive to fabricate than scroll expanders.
**** Reciprocating piston expander
     Reciprocating machines have a good isentropic efficiency (about 70%) and a good power output/size ratio. Endo et al. from Honda R&D chose volumetric axial piston as the expanding machine for their RC system due to its low operating speed and comparatively  at efficiency characteristics compared to turbine expander. In general, piston expanders show some advantages over other expansion machines, such as larger built-in volume ratio, high achievable operating pressures and temperatures, ability to tolerate two-phase flow and low rotational speeds.
     

*** Working Fluids
Special attention should be paid to the working fluid selection according to the heat source temperature, which has a significant effect on the system thermal and exergetic efficiency. When implementing a RC system to a passenger vehicle is considered, stricter criterion should be adopted for the fluid selection to minimize the harm potential to passengers in case leakages or crashes happen, e.g. low flammability level is a major concern for passenger vehicle application. Therefore, alcohols and hydrocarbons, in spite of their good thermodynamic efficiencies, are arguably not the best candidates. Instead, the refrigerants, which have already been used in automotive AC systems, are usually better options. Generally, according to the slope of the saturation curve, the working fluid can be categorized into three different types, wet fluid, dry fluid and isentropic fluid.
Most inorganic fluids are wet fluids, but this means that the expansion ends in two-phase region. Water has been used by auto manufacturers like Honda and BMW, bugt according to Arias et al. when water was selected as the working fluid, the waste heat from the engine coolant wouldn’t be effectively recovered by the system due to the mismatch between the low temperature of engine coolant and high boiling temperature of water.
