* Introduction to the problem
On-road vehicles, which convert around one third of the fuel energy into useful mechanical energy for propulsion, are moving energy conversion systems that generate considerable waste heat. Due to the inefficiency of the internal combustion engine, around 60-70% of the fuel energy is wasted in the form of heat.
Rankine cycle has a great potential to be applied to harvest waste heat from automobiles. However, different from other low-grade waste heat sources, vehicles have limited space for the RC system integration and the waste heat is relatively unstable.
It has been estimated that the thermal efficiency of a modern IC engine is limited to 20-40% while 33% of the fuel energy from a typical medium-size passenger vehicle is carried away by exhaust gases and 29% is carried away by engine cooling water in urban traffic conditions. Depending on engine type and operating conditions, the IC exhaust gas temperature usually varies from 500 to 900 °C and engine cooling water temperature is around 100 °C.

There are different possibile technologies that are being researched in order to 
[Zhou Dede Joshi]

* Possibile solutions
** Rankine cycle
The RC system is an interesting system to harvest part of the wasted energy. An RC system is made of four main components:
- Evaporator
- Expander
- Condenser
- Pump

The waste heat is used in the evaporator to vaporize the working fluid and convert the heat in mechanical work in the expander.
Extensive work has been poured in RC + ICE combinations, leading to fuel saving in the order of 10 - 15% when applied to truck diesel engines.

RC are system widely adopted in a large range of WHR situations, however heat sources on vehicles are different from other typical industrial heat sources, which are stable and no space limitation for the RC system. To be technically feasible for vehicle RC application, the cycle system should be kept as simple as possible and utilize components that already exist in the vehicles in order to reduce the added expense, weight and complexity of the system. Besides, the temperature ranges of the two main heat sources on vehicles are significantly different which requires special treatment.

*** Possible configurations - advantages and disadvantages

*[INSERISCI FIGURE DA TOYOTA]*

The most common and simple structure utilizes the exhaust gas as the only heat source to evaporate the working fluid. The second structure adds another heat exchanger (recuperator) before the evaporator, using the steam from the expander to preheat the working fluid. A third structure uses waste heat from engine coolant to preheat the working fluid. The regenerative preheating of structure 2 requires a very complex liquid-gas heat exchanger with high exchange surfaces, while the preheater in structure 3 only requires a simple liquid-liquid heat exchanger.
There have been contradicting conclusions about the effect of preheating using engine coolant on the RC system efficiency. Based on Vaja and Gambarotta’s work, the RC system with a preheater allows a net increase in power output, compared to structure 1, of 10% to 35%, depending on which working fluid is chosen. Alberto Boretti also showed a 8.2% fuel economy improvement using engine coolant to preheat the RC cycle, compared to a 6.4% improvement when only exhaust gas is used to boil the working fluid. Arias et al. also compared the combined exhaust and engine coolant heat recovery system with the exhaust only structure. It was found that the additional power recovered from the engine coolant system was 20W out of a total 2140W, which is around 1% improvement.
It was argued that the reason why it is not advantageous to build combined engine coolant and exhaust gas waste heat recovery system is due to the constraint imposed on the engine coolant temperature, around 100 °C, is not a good match for the working fluid preheating. Duparchy et al. also analyzed the waste heat recovery potential for engine cooling water and exhaust gas from both energy and exergy points of view. It was found that the proportion of thermal energy carried by exhaust gas is comparable with that dissipated by engine cooling water, which means these two sources are roughly equivalent from the energy point of view. However, exhaust gas shows a much greater recovery potential in terms of exergy. The main reason why opposite conclusions were drawn from different studies is that different working fluid is selected for the RC system. For organic fluids, the preheating energy ranges 30% to 50% of the total obtained energy while it is only about 10% for water.

There are two additional configurations possible for WHR. Instead of using engine coolant to preheat the working  uid, the engine block, which has higher temperature, is used to partially evaporate the working fluid. For this structure, complete evaporation of the working  uid inside the engine block should be prevented. It should reach intermediate boiling in the engine block, so that two-phase mixture would flow out of the engine block and into the evaporator to complete the boiling and superheating process by exhaust gas. The second option is to build separate system loops and use different working fluids to match the speci c characteristics of engine coolant and exhaust gas. This system has been developed by BMW, in which waster was used as the medium in the high-temperature (HT) loop and ethanol as working fluid in the low-temperature (LT) loop. The dual loop system can utilize the full potential of the waste energy with the disadvantage of large system volume and system complexity. Another RC system which integrated with engine cooling, this system minimized the number of required components by adopting an evaporative engine cooling structure and a refrigerant as the working fluid, so that the engine functioned as an evaporator and the existing radiator worked as a condenser. The only extra component added to the system is an expander for power conversion. However, this structure requires a modification of the existing engine cooling system, while the current engine cooling technology is quite mature and widely taken and has been using 50/50 water ethylene glycol as the coolant for decades.

When selecting the different configurations, different factors have to be take into consideration as the maximization of the recovered energy is not the only objective to pursue. System complexity, component volume and weight, and the resulted extra cost added to the vehicles and the payback period are also big concerns.
