* IDEAS
- Focalizzarsi sulla mobilità ibrida e quindi usare il sistema di WHR per produrre energia elettrica. Questo permetterebbe di pensare a una turbina ad azione e non scroll, possibile aumento dell'efficenza. Ibrido futuro?
- Quanto ci perdiamo con lo scroll? La penalità di peso è eccessiva?

* TO-DO list
** TODO Working fluids
** TODO Properties of organic fluids
** TODO Super-critical principles
** TODO Weight influence on fuel consumption
** TODO Capire bene l'influenza delle perdite di pressione e se usare il sistema evaporative cooling potrebbe aiutare (reference 70)
** TODO Integration of the WHR with a battery pack 
** TODO Compare efficiencies of different expanders at variable mass flow rate
** TODO Boretti document
** TODO Mathematical modeling of a super-critical CO2 cycle
* Introduction to the problem
On-road vehicles, which convert around one third of the fuel energy into useful mechanical energy for propulsion, are moving energy conversion systems that generate considerable waste heat. Due to the inefficiency of the internal combustion engine, around 60-70% of the fuel energy is wasted in the form of heat. Caton indicates that approximately 40% of the fuel energy leaves the engine in the hot exhaust and another another 30% is lost as heat.  Regardless of how efficient the engine is, there will still be a significant fraction of the fuel energy that is rejected in the exhaust and coolant streams.
Rankine cycle has a great potential to be applied to harvest waste heat from automobiles. However, different from other low-grade waste heat sources, vehicles have limited space for the RC system integration and the waste heat is relatively unstable.
It has been estimated that the thermal efficiency of a modern IC engine is limited to 20-40% while 33% of the fuel energy from a typical medium-size passenger vehicle is carried away by exhaust gases and 29% is carried away by engine cooling water in urban traffic conditions. Depending on engine type and operating conditions, the IC exhaust gas temperature usually varies from 500 to 900 °C and engine cooling water temperature is around 100 °C.
Engine coolant and exhaust gas are two main heat sources in a vehicle, which carry a similar amount of thermal energy. However, exhaust gas shows a much greater recovery potential in terms of exergy because of a much higher temperature range. For this reason, recover heat from the two sources using the same loop and same working fluid might not be appropriate due to the potential mismatch between fluid properties and heat sources temperature ranges. The waste heat from the engine could be harvested either by pumping the working fluid through the engine block or using a separate loop and different working fluids.

* Possibile solutions
** Organic Rankine Cycle
Organic Rankine Cycle (ORC), which uses an organic fluid with a low boiling point working medium, is considered as the most promising technology to recover energy from low-grade waste heat.
The RC system is an interesting system to harvest part of the wasted energy. An RC system is made of four main components:
- Evaporator
- Expander
- Condenser
- Pump

The waste heat is used in the evaporator to vaporize the working fluid and convert the heat in mechanical work in the expander.
Extensive work has been poured in RC + ICE combinations, leading to fuel saving in the order of 10 - 15% when applied to truck diesel engines.

RC are system widely adopted in a large range of WHR situations, however heat sources on vehicles are different from other typical industrial heat sources, which are stable and no space limitation for the RC system. To be technically feasible for vehicle RC application, the cycle system should be kept as simple as possible and utilize components that already exist in the vehicles in order to reduce the added expense, weight and complexity of the system. Besides, the temperature ranges of the two main heat sources on vehicles are significantly different which requires special treatment.

*** Possible configurations - advantages and disadvantages

*[INSERISCI FIGURE DA TOYOTA]*

The most common and simple structure utilizes the exhaust gas as the only heat source to evaporate the working fluid. The second structure adds another heat exchanger (recuperator) before the evaporator, using the steam from the expander to preheat the working fluid. A third structure uses waste heat from engine coolant to preheat the working fluid. The regenerative preheating of structure 2 requires a very complex liquid-gas heat exchanger with high exchange surfaces, while the preheater in structure 3 only requires a simple liquid-liquid heat exchanger.
There have been contradicting conclusions about the effect of preheating using engine coolant on the RC system efficiency. Based on Vaja and Gambarotta’s work, the RC system with a preheater allows a net increase in power output, compared to structure 1, of 10% to 35%, depending on which working fluid is chosen. Alberto Boretti also showed a 8.2% fuel economy improvement using engine coolant to preheat the RC cycle, compared to a 6.4% improvement when only exhaust gas is used to boil the working fluid. Arias et al. also compared the combined exhaust and engine coolant heat recovery system with the exhaust only structure. It was found that the additional power recovered from the engine coolant system was 20W out of a total 2140W, which is around 1% improvement.
It was argued that the reason why it is not advantageous to build combined engine coolant and exhaust gas waste heat recovery system is due to the constraint imposed on the engine coolant temperature, around 100 °C, is not a good match for the working fluid preheating. Duparchy et al. also analyzed the waste heat recovery potential for engine cooling water and exhaust gas from both energy and exergy points of view. It was found that the proportion of thermal energy carried by exhaust gas is comparable with that dissipated by engine cooling water, which means these two sources are roughly equivalent from the energy point of view. However, exhaust gas shows a much greater recovery potential in terms of exergy. The main reason why opposite conclusions were drawn from different studies is that different working fluid is selected for the RC system. For organic fluids, the preheating energy ranges 30% to 50% of the total obtained energy while it is only about 10% for water.

There are two additional configurations possible for WHR. Instead of using engine coolant to preheat the working  uid, the engine block, which has higher temperature, is used to partially evaporate the working fluid. For this structure, complete evaporation of the working  uid inside the engine block should be prevented. It should reach intermediate boiling in the engine block, so that two-phase mixture would flow out of the engine block and into the evaporator to complete the boiling and superheating process by exhaust gas. The second option is to build separate system loops and use different working fluids to match the speci c characteristics of engine coolant and exhaust gas. This system has been developed by BMW, in which waster was used as the medium in the high-temperature (HT) loop and ethanol as working fluid in the low-temperature (LT) loop. The dual loop system can utilize the full potential of the waste energy with the disadvantage of large system volume and system complexity. Another RC system which integrated with engine cooling, this system minimized the number of required components by adopting an evaporative engine cooling structure and a refrigerant as the working fluid, so that the engine functioned as an evaporator and the existing radiator worked as a condenser. The only extra component added to the system is an expander for power conversion. However, this structure requires a modification of the existing engine cooling system, while the current engine cooling technology is quite mature and widely taken and has been using 50/50 water ethylene glycol as the coolant for decades.

When selecting the different configurations, different factors have to be take into consideration as the maximization of the recovered energy is not the only objective to pursue. System complexity, component volume and weight, and the resulted extra cost added to the vehicles and the payback period are also big concerns.

**** Dual-loop systems (University of glasgow)
A dual-loop ORC is presented to simultaneously recover energy from both the exhaust gases and the coolant of a petrol engine. A high-temperature (HT) ORC loop is used to recover heat from the exhaust gases, while a low-temperature (LT) ORC loop is used to recover heat from the coolant and the condensation heat of the HT loop.
The results show that the dual-loop ORC can effectively recover the waste heat from the petrol engine, as reported in the table:

| Regime         | Thermal efficiency increase |
|----------------+-----------------------------|
| high - speed   | 20 - 24 %                   |
| medium - speed | 14 - 20 %                   |
| low - speed    | 30 %                        |

Because the temperatures and thermodynamic properties of the exhaust and coolant from an internal combustion engine differ a lot, it is impossible to find a simple ORC architecture to complete heat recovery of these two kinds of waste heat simultaneously. Many different ORC systems were proposed for engine waste recovery. Currently, a dual-loop cycle designed by BMW has caused the greatest attention. Freymann et al, 2008, employed water and ethanol as the working fluids for BMW’s schematic. Because both water and ethanol are wet fluids, large irreversibility will be produced during the heat transfer processes.
Wang et al, 2012, Zhang et al, 2013, and Yang et al, 2014, proposed a dual-loop ORC system using R245fa and R134a as working fluids and estimated their energy saving potential for gasoline and diesel engines, respectively. Meanwhile, Shu et al, 2014, Song and Gu, 2015, studied the performances of dual-loop ORCs using different working fluids.

[INSERIRE SCHEMATICO DEL CICLO A DOPPIO LOOP E DIAGRAMMA T-S]

The thermal efficiency of the HT loop with R1233zd is slightly higher than that of the R245fa. On the other hand, the thermal efficiencies of the LT loop using R1234yf are slighter lower than those of the R134a under all the ambient temperatures. As a result, the thermodynamic performance of the dual-loop ORC with R1233zd and R1234yf is slightly higher than that with R245fa and R134a. However, the dual-loop ORC with R1233zd and R1234yf has better environmental performance and thus more suitable for engine waste heat recovery.

**** WHR for light duty diesel engines (Thomas Briggs etc.)
Lab demonstration was designed to maximize the peak brake thermal efficiency of the engine, and the combined system achieved an efficiency of 45%. A modern automotive diesel engine can easily achieve a 42% brake thermal efficiency at its optimum operating point.
The high load factor of heavy-duty engines was deemed a more appropriate match to bottoming cycles. However, in recent years there has been an increased emphasis on light-duty vehicle efficiency as well.
The organic Rankine cycle system was installed on a General Motors 1.9-liter diesel engine. The high exhaust temperature drove the selection of exhaust heat as the energy source for the ORC. Since the ORC impacts the backpressure on the engine and therefore its performance it is necessary to analyze the change in efficiency between the engine-only and engine +ORC operating cases.
Engine operation was not significantly affected by the addition of the ORC heat exchangers to the exhaust system. The backpressure at the turbine exit was increased by 13.8 kPa; this is a similar backpressure increase as a muffler would provide. Past researchers have found that the heat exchangers can replace the muffler in a vehicle, eliminating the additional loss that would otherwise be expected.
**** Evaporative engine cooling system
Evaporative engine cooling system is utilized to obtain high thermal efficiency and simplicity of the Rankine bottoming system. There is the possivility for the application of Rankine bottoming system to passenger cars, with an attempt made to combine the evaporative engine cooling system and Rankine bottoming system for the simplification of system.
In case of passenger cars, however, the temperature and calorific value of exhaust gas tend to fluctuate markedly because of frequent repetition of starting and stopping in urban areas, which are different from the running pattern of trucks used for long-distance transportation.
*** Applications to passenger vehicles to date

**** Possible efficiency improvements
Two improvements are mainly used in the literature to asses the impact of RC systems: /thermal efficiency/ and /mechanical efficiency/.
Thermal efficiency is defined as 
\begin{equation}
\eta_{th} = \frac{W_{RC}}{m_{fuel} \cdot LHV}
\end{equation}
while mechanical efficiency is defined as 
\begin{equation}
\eta_{m} = \frac{W_{RC}}{P_{e}}
\end{equation}

Assuming one third of the total fuel energy is transferred to mechanical power output, which is a typical value for modern internal combustion engine, then usually the thermal efficiency is about one third of the mechanical efficiency.

**** Historical review
| Year | Researcher           | Technology           | % power recovered | $\Delta$ c thermal $\eta$ | $\Delta$ mechanical $\eta$ |
|------+----------------------+----------------------+-------------------+---------------------------+----------------------------|
| 1993 | Toyota               |                      |                3% |                        1% |                            |
|      | Chammas and Clodic   | steam RC             |                   |                        4% |                            |
|      | Chammas and Clodic   | organic RC           |                   |                        5% |                            |
|      | Arias, Shedd, Jester | System 4             |              5.5% |       7.5% da controllare |                            |
| 2007 | Honda R&D            | RC with hybrid       |                   |   28.9% - 32.7% @100 km/h |                            |
| 2008 | BMW                  | turbosteamer         |           10-15 % |                      5.7% |                            |
| 2012 | BMW                  | turbosteamer 2       |                6% |                        2% |                            |
|      | He et al.            | Kalina cycle         |                   |                  12-17.3% |                            |
|      | Wand et al.          | Dual loop + extra HX |          14 - 40% |                      3-6% |                            |
|      | Domingues et al.     | Simplest RC system   |                   |                           | 2.64 - 6.96%               |
                                                                                                                                                                                                                                                                   
*** Expanders
Critical aspect that has to be chosen carefully. Many factors need to be considered during the process of expander selection for a RC system targeting passenger vehicles, e.g. inlet and outlet working conditions, pressure ratio, power output, working  uid, weight, volume, cost, reliability, isentropic ef ciency, lubrication requirement, complexity, rotational speed, etc. In general, expander can be categorized into two types: velocity type, e.g. axial turbine expander, and volume type, e.g. scroll expander, screw expander and reciprocal piston expander.

**** Turbine expander
A turbine expander is rotary machine that converts the kinetic energy carried by a fluid stream into mechanical energy when it passes through a set of blades. Commercial micro-turbines available but not widely used (Domingues). The reduced mass and overall dimensions made the turbine one of the most appropriate expander for a RC vehicle waste heat recovery application. Due to the lack of commercial micro-turbine expanders, most researchers used their in-house speci cally designed turbine to test their RC system, usually impulse turbines. BMW’s second generation Turbosteamer  adopted a speci cally designed two-stage impulse turbine integrated with an electric generator for their RC system, see Figure 8. The turbine works in the pressure range of 6-10 bar and the rotary speed is about 50,000 to 100,000 rpm. The electrical power output of the unit is about a 2 kW. Compared to a scaled-down reaction turbine which is generally used in power plants, the impulse turbine design signi cantly reduces the  ow leakage. Lubrication free is another advantage of this design compared to volumetric expansion machines.
In general, the advantages of a turbine expander include compact structure, light weight and high ef ciency. However, the design and manufacturing of turbine is very dif cult, which leads to a relatively higher cost and the turbine ef ciency decreases signi cantly under off-design conditions. Besides, a turbine expander puts more constraints to the working  uid selection since a turbine cannot bear two-phase condition. Therefore if the heat addition is variable, the wetness in the expansion process may become uncontrollable and the droplets may damage the turbine blades. Also, a speed reduction gearbox might be required if the turbine outputs the mechanical energy directly to the crank shaft due to the speed mismatch. It is suggested that turbine expanders are preferred to be combined with electrical generators for energy conversion and storage, which make it a practical solution for hybrid vehicles.
It is *more suitable to be combined with electrical generators* for energy conversion.

**** Scroll Expander
Scroll expander is one of the displacement type expanding machines, which are characterized by lower  ow rates, higher pressure ratios and much lower rotational speeds than turbo-machines. Advantages of this kind of technology are compact structure, reliability, fewer moving parts, lower level of noise and vibration. Besides, compare to turbine expander, these displacement type machines can tolerate two-phase conditions, which may difficult to be avoided at the end of the expansion considering the dynamic operating conditions in vehicles.
For RC system with small power output, leakage of the working  uid was the dominant cause of low ef ciency of scroll expander. The first RC application to passenger vehicle study from Toyota adopted a scroll expander which had an inlet volume of 40 cc and an expansion ratio of 2. The size of the scroll expander is 120 mm by 190 mm. The maximum expander efficiency reached in the study is approximately 50%. It was found that the expander ef ciency decreases as the revolution became lower than 1000 rpm due to the deterioration of sealing at low revolution speed which led to leakage of the working fluid.

**** Screw Expander
This type of expander is composed of a pair of meshing helical rotors, packing within a case with approximately 50 μm clearances. When the rotors rotate, the volume trapped between the rotors and the casing changes, which makes the fluid volume either increase or decrease, depending on the rotational direction. However, micro-scale screw expander (<10 kWe) for vehicle application is hard to be obtained in the current market and few reports from open literature were found for screw expander application to RC system with power output lower than 10 kWe.
In general, screw expander can tolerate two-phase flow and is highly efficient in off-design conditions. However, like other positive displacement devices, the seal is critical to prevent internal leakage. Besides, lubrication is required to avoid direct contact but also achieve a seal between the lobes of the two rotors, which makes it relatively more expensive to fabricate than scroll expanders.
**** Reciprocating piston expander
     Reciprocating machines have a good isentropic efficiency (about 70%) and a good power output/size ratio. Endo et al. from Honda R&D chose volumetric axial piston as the expanding machine for their RC system due to its low operating speed and comparatively  at efficiency characteristics compared to turbine expander. In general, piston expanders show some advantages over other expansion machines, such as larger built-in volume ratio, high achievable operating pressures and temperatures, ability to tolerate two-phase flow and low rotational speeds.
     
*** Working Fluids
Special attention should be paid to the working fluid selection according to the heat source temperature, which has a significant effect on the system thermal and exergetic efficiency. When implementing a RC system to a passenger vehicle is considered, stricter criterion should be adopted for the fluid selection to minimize the harm potential to passengers in case leakages or crashes happen, e.g. low flammability level is a major concern for passenger vehicle application. Therefore, alcohols and hydrocarbons, in spite of their good thermodynamic efficiencies, are arguably not the best candidates. Instead, the refrigerants, which have already been used in automotive AC systems, are usually better options. Generally, according to the slope of the saturation curve, the working fluid can be categorized into three different types, wet fluid, dry fluid and isentropic fluid.
Most inorganic fluids are wet fluids, but this means that the expansion ends in two-phase region. Water has been used by auto manufacturers like Honda and BMW, but according to Arias et al. when water was selected as the working fluid, the waste heat from the engine coolant wouldn’t be effectively recovered by the system due to the mismatch between the low temperature of engine coolant and high boiling temperature of water. Therefore, it is safe to conclude that water is a preferable working fluid for high exhaust gas temperature ranging from 500 to 800 °C.

*[INSERIRE GRAFICO DEI FLUIDI CON LE DIFFERENZA, CARINO DA TOYOTA]*

There are a few disadvantages of water, such as the requirement for superheating to avoid turbine blade erosion if turbine is selected to be the expander, but the high degree of superheating makes it less practical for automotive application due to the variation of exhaust temperature at different load conditions. Besides, its high freezing point (0°C) cannot meet the standard automotive working temperature range (-40 ∼ 85°C).
The dry/isentropic refrigerants are widely used in small-scale RC applications because of their good heat transfer properties, excellent thermal stability and low viscosity. They are generally non-flammable, which is a big advantage for automotive application and compatible with most materials. Under typical low temperature ambient conditions they do not freeze, which is a major concern with water. Chammas and Clodic compared different organic fluids with water for RC application to hybrid vehicles and argued that using water for RC system to recover automotive waste heat could lead to a complex system requiring large size equipment and high investment cost, which makes the study on organic working fluid necessary.
Domingues et al. compared R123 and R245fa with water as working fluid for vehicle RC waste heat recovery potential from exhaust gas. The study revealed the advantage of using water as RC working fluid to recover waste heat from exhaust gas of vehicles equipped with spark-ignition engine. However, it was also found that the heat exchanger effectiveness for R123 and R245fa is higher than that for water, and consequently when the exhasut temperature is relatively low, organic fluids can be considered appropriate for vehicle RC application. Wang et al. studied the RC system with nine different pure organic working fluids for engine waste heat recovery. The results indicated that R11, R141b, R113 and R123 presented slightly higher thermodynamic performances while R245fa and R245ca are the most envrionmentfriendly working fluids for engine waste heat revocery applications.
The dry/isentropic organic fluids have a few shortcomings. First, the intrisic property of dry/isentropic fluids reduce the area of net work in the T-s diagram, which means less power output compared to wet fluid, e.g. water. Second, to reduce the cooling load of the condenser, a recuperator (liquid-gas heat exchagner) is usually necessary to cool the superheated vapor to saturated state, which increases the system complexity and cost. Besides, most organic fluids have relatively low thermal instability temperatures compared to water, therefore at high temperature and pressure, the system might suffer chemical decomposition and deterioration. In addition, the current generation of refrigerants, e.g. HFCs (hydroflurocarbons), has a high global warming potential, which means that their use could be limited or banned in the near future. 

**** List of possible working fluids

- Ethanol
- R134a
- R236fa
- R245fa
- R1233zd (for high temperature)
- R1234yf (for low temperature), both have lower toxicities than the two before but similar characteristics
- HCFC123

* System integration
To utilize the waste heat from vehicles via Rankine cycle system, a best compromise between the system complexity and fuel saving potential needs to be found out. Regarding vehicle integration, it is widely acknowledged that how to minimize the system complexity, weight, costs and the negative effect on the existing components is more important than maximizing the RC power output.

** Influence of the added weight
An increased vehicle weight cannot be avoided due to extra system components, which would lead to more tractive effort required to accelerate the vehicle and more rolling resistance from the tires. It is roughly estimated that for every 100 pounds added to the vehicle, the fuel economy is decreased by 1-2 percent. For small passenger vehicles, the added-on weight has more impact to the fuel economy than it does on the long-haul diesel truck.

** Influence of the added machinery/hardware
A heat exchanger is necessary to transmit the heat from exhaust gas to working fluid of the RC system at excellent efficiency, which will increase the engine back pressure and affect the engine performance, followed by a large horsepower loss. Therefore the overall added exhaust back pressure should be limited to avoid big engine performance deterioration. On the other hand, the evaporator lowers the exhaust gas temperature, which decreases the exhaust gas velocity and thus a smaller pressure loss through the piping and components following the evaporator. Both effects should be considered when the engine back pressure increment is calculated. Boretti claimed that turbocharged engines may better work with an increased back pressure than naturally aspirated engines.
The heat coming from the RC condenser needs to be dissipated to the environment, which increases the cooling demand of the vehicles. There are basically two ways to condense the RC work fluid, a separate air-cooled condenser and integrating into the existing engine cooling loop. The downside of this integration strategy is that the engine coolant temperature at the condenser inlet may be too high to completely condense and sub-cool the RC working fluid. Also the available cooling capacity of the radiator may not be enough, which will restrict the condenser heat rejection and thus RC power output. In addition, additional heat transferred to the engine cooling loop requires a coolant circulation at higher speed and higher cooling air velocity, which lead to an increase coolant pump power consumption and increase air flow resistance. On the other hand, keeping the two components separated leads to an increased space needed for installation and increased air resistance.

** How to use the energy produced
Generally there are two ways to use this recovered energy: outputting the mechanical energy directly to the crank shaft and combining the RC system with electrical generators to convert the mechanical energy into electricity. For small passenger vehicles, the driving profile is not stable which leads to a fluctuating exhaust gas temperature, then the second method seems to be a more reasonable option.
